name: Run API Tests

on:
  pull_request:
    branches:
      - stage

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ” Checkout code
        uses: actions/checkout@v4

      - name: ğŸ§ª Setup up Nodejs
        uses: actions/setup-node@v4
        with:
          node-version:  22.x

      - name: ğŸš€ Install dependencies
        run: npm install
        working-directory: api

      - name: ğŸ§ª Run tests
        run: npm run test
        working-directory: api
